// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="filter11x11_strm,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu9p-flga2104-2-i,HLS_INPUT_CLOCK=6.660000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=5.728000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=44,HLS_SYN_DSP=48,HLS_SYN_FF=1791,HLS_SYN_LUT=3299,HLS_VERSION=2019_2}" *)

module filter11x11_strm (
        width,
        height,
        src_V_TDATA,
        dst_V_TDATA,
        ap_clk,
        ap_rst_n,
        ap_start,
        src_V_TVALID,
        src_V_TREADY,
        dst_V_TVALID,
        dst_V_TREADY,
        ap_done,
        ap_ready,
        ap_idle
);


input  [31:0] width;
input  [31:0] height;
input  [31:0] src_V_TDATA;
output  [31:0] dst_V_TDATA;
input   ap_clk;
input   ap_rst_n;
input   ap_start;
input   src_V_TVALID;
output   src_V_TREADY;
output   dst_V_TVALID;
input   dst_V_TREADY;
output   ap_done;
output   ap_ready;
output   ap_idle;

 reg    ap_rst_n_inv;
wire    filter11x11_strm_ent_U0_ap_start;
wire    filter11x11_strm_ent_U0_ap_done;
wire    filter11x11_strm_ent_U0_ap_continue;
wire    filter11x11_strm_ent_U0_ap_idle;
wire    filter11x11_strm_ent_U0_ap_ready;
wire    filter11x11_strm_ent_U0_start_out;
wire    filter11x11_strm_ent_U0_start_write;
wire   [31:0] filter11x11_strm_ent_U0_width_out_din;
wire    filter11x11_strm_ent_U0_width_out_write;
wire   [31:0] filter11x11_strm_ent_U0_width_out1_din;
wire    filter11x11_strm_ent_U0_width_out1_write;
wire   [31:0] filter11x11_strm_ent_U0_height_out_din;
wire    filter11x11_strm_ent_U0_height_out_write;
wire   [31:0] filter11x11_strm_ent_U0_height_out2_din;
wire    filter11x11_strm_ent_U0_height_out2_write;
wire    Block_proc_U0_ap_start;
wire    Block_proc_U0_ap_done;
wire    Block_proc_U0_ap_continue;
wire    Block_proc_U0_ap_idle;
wire    Block_proc_U0_ap_ready;
wire    Block_proc_U0_start_out;
wire    Block_proc_U0_start_write;
wire    Block_proc_U0_width_read;
wire    Block_proc_U0_height_read;
wire   [31:0] Block_proc_U0_width_out_din;
wire    Block_proc_U0_width_out_write;
wire   [31:0] Block_proc_U0_height_out_din;
wire    Block_proc_U0_height_out_write;
wire   [31:0] Block_proc_U0_vconv_xlim_out_out_din;
wire    Block_proc_U0_vconv_xlim_out_out_write;
wire    Loop_HConvH_proc6_U0_ap_start;
wire    Loop_HConvH_proc6_U0_ap_done;
wire    Loop_HConvH_proc6_U0_ap_continue;
wire    Loop_HConvH_proc6_U0_ap_idle;
wire    Loop_HConvH_proc6_U0_ap_ready;
wire    Loop_HConvH_proc6_U0_start_out;
wire    Loop_HConvH_proc6_U0_start_write;
wire    Loop_HConvH_proc6_U0_height_read;
wire    Loop_HConvH_proc6_U0_width_read;
wire    Loop_HConvH_proc6_U0_src_V_TREADY;
wire   [31:0] Loop_HConvH_proc6_U0_hconv_V_din;
wire    Loop_HConvH_proc6_U0_hconv_V_write;
wire    Loop_VConvH_proc_U0_ap_start;
wire    Loop_VConvH_proc_U0_ap_done;
wire    Loop_VConvH_proc_U0_ap_continue;
wire    Loop_VConvH_proc_U0_ap_idle;
wire    Loop_VConvH_proc_U0_ap_ready;
wire    Loop_VConvH_proc_U0_height_read;
wire    Loop_VConvH_proc_U0_vconv_xlim_loc_read;
wire    Loop_VConvH_proc_U0_hconv_V_read;
wire   [31:0] Loop_VConvH_proc_U0_vconv_V_din;
wire    Loop_VConvH_proc_U0_vconv_V_write;
wire   [31:0] Loop_VConvH_proc_U0_height_out_din;
wire    Loop_VConvH_proc_U0_height_out_write;
wire   [31:0] Loop_VConvH_proc_U0_vconv_xlim_loc_out_din;
wire    Loop_VConvH_proc_U0_vconv_xlim_loc_out_write;
wire    Loop_Border_proc_U0_ap_start;
wire    Loop_Border_proc_U0_ap_done;
wire    Loop_Border_proc_U0_ap_continue;
wire    Loop_Border_proc_U0_ap_idle;
wire    Loop_Border_proc_U0_ap_ready;
wire    Loop_Border_proc_U0_width_read;
wire    Loop_Border_proc_U0_height_read;
wire   [31:0] Loop_Border_proc_U0_dst_V_TDATA;
wire    Loop_Border_proc_U0_dst_V_TVALID;
wire    Loop_Border_proc_U0_vconv_xlim_loc_read;
wire    Loop_Border_proc_U0_vconv_V_read;
wire    ap_sync_continue;
wire    width_c_full_n;
wire   [31:0] width_c_dout;
wire    width_c_empty_n;
wire    width_c163_full_n;
wire   [31:0] width_c163_dout;
wire    width_c163_empty_n;
wire    height_c_full_n;
wire   [31:0] height_c_dout;
wire    height_c_empty_n;
wire    height_c164_full_n;
wire   [31:0] height_c164_dout;
wire    height_c164_empty_n;
wire    width_c165_full_n;
wire   [31:0] width_c165_dout;
wire    width_c165_empty_n;
wire    height_c166_full_n;
wire   [31:0] height_c166_dout;
wire    height_c166_empty_n;
wire    vconv_xlim_loc_c_full_n;
wire   [31:0] vconv_xlim_loc_c_dout;
wire    vconv_xlim_loc_c_empty_n;
wire    hconv_V_full_n;
wire   [31:0] hconv_V_dout;
wire    hconv_V_empty_n;
wire    vconv_V_full_n;
wire   [31:0] vconv_V_dout;
wire    vconv_V_empty_n;
wire    height_c167_full_n;
wire   [31:0] height_c167_dout;
wire    height_c167_empty_n;
wire    vconv_xlim_loc_c168_full_n;
wire   [31:0] vconv_xlim_loc_c168_dout;
wire    vconv_xlim_loc_c168_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
reg    ap_sync_reg_filter11x11_strm_ent_U0_ap_ready;
wire    ap_sync_filter11x11_strm_ent_U0_ap_ready;
reg   [1:0] filter11x11_strm_ent_U0_ap_ready_count;
reg    ap_sync_reg_Loop_HConvH_proc6_U0_ap_ready;
wire    ap_sync_Loop_HConvH_proc6_U0_ap_ready;
reg   [1:0] Loop_HConvH_proc6_U0_ap_ready_count;
wire   [0:0] start_for_Block_proc_U0_din;
wire    start_for_Block_proc_U0_full_n;
wire   [0:0] start_for_Block_proc_U0_dout;
wire    start_for_Block_proc_U0_empty_n;
wire   [0:0] start_for_Loop_Border_proc_U0_din;
wire    start_for_Loop_Border_proc_U0_full_n;
wire   [0:0] start_for_Loop_Border_proc_U0_dout;
wire    start_for_Loop_Border_proc_U0_empty_n;
wire   [0:0] start_for_Loop_VConvH_proc_U0_din;
wire    start_for_Loop_VConvH_proc_U0_full_n;
wire   [0:0] start_for_Loop_VConvH_proc_U0_dout;
wire    start_for_Loop_VConvH_proc_U0_empty_n;
wire    Loop_VConvH_proc_U0_start_full_n;
wire    Loop_VConvH_proc_U0_start_write;
wire    Loop_Border_proc_U0_start_full_n;
wire    Loop_Border_proc_U0_start_write;

// power-on initialization
initial begin
#0 ap_sync_reg_filter11x11_strm_ent_U0_ap_ready = 1'b0;
#0 filter11x11_strm_ent_U0_ap_ready_count = 2'd0;
#0 ap_sync_reg_Loop_HConvH_proc6_U0_ap_ready = 1'b0;
#0 Loop_HConvH_proc6_U0_ap_ready_count = 2'd0;
end

filter11x11_strm_ent filter11x11_strm_ent_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(filter11x11_strm_ent_U0_ap_start),
    .start_full_n(start_for_Block_proc_U0_full_n),
    .ap_done(filter11x11_strm_ent_U0_ap_done),
    .ap_continue(filter11x11_strm_ent_U0_ap_continue),
    .ap_idle(filter11x11_strm_ent_U0_ap_idle),
    .ap_ready(filter11x11_strm_ent_U0_ap_ready),
    .start_out(filter11x11_strm_ent_U0_start_out),
    .start_write(filter11x11_strm_ent_U0_start_write),
    .width(width),
    .height(height),
    .width_out_din(filter11x11_strm_ent_U0_width_out_din),
    .width_out_full_n(width_c_full_n),
    .width_out_write(filter11x11_strm_ent_U0_width_out_write),
    .width_out1_din(filter11x11_strm_ent_U0_width_out1_din),
    .width_out1_full_n(width_c163_full_n),
    .width_out1_write(filter11x11_strm_ent_U0_width_out1_write),
    .height_out_din(filter11x11_strm_ent_U0_height_out_din),
    .height_out_full_n(height_c_full_n),
    .height_out_write(filter11x11_strm_ent_U0_height_out_write),
    .height_out2_din(filter11x11_strm_ent_U0_height_out2_din),
    .height_out2_full_n(height_c164_full_n),
    .height_out2_write(filter11x11_strm_ent_U0_height_out2_write)
);

Block_proc Block_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Block_proc_U0_ap_start),
    .start_full_n(start_for_Loop_Border_proc_U0_full_n),
    .ap_done(Block_proc_U0_ap_done),
    .ap_continue(Block_proc_U0_ap_continue),
    .ap_idle(Block_proc_U0_ap_idle),
    .ap_ready(Block_proc_U0_ap_ready),
    .start_out(Block_proc_U0_start_out),
    .start_write(Block_proc_U0_start_write),
    .width_dout(width_c_dout),
    .width_empty_n(width_c_empty_n),
    .width_read(Block_proc_U0_width_read),
    .height_dout(height_c_dout),
    .height_empty_n(height_c_empty_n),
    .height_read(Block_proc_U0_height_read),
    .width_out_din(Block_proc_U0_width_out_din),
    .width_out_full_n(width_c165_full_n),
    .width_out_write(Block_proc_U0_width_out_write),
    .height_out_din(Block_proc_U0_height_out_din),
    .height_out_full_n(height_c166_full_n),
    .height_out_write(Block_proc_U0_height_out_write),
    .vconv_xlim_out_out_din(Block_proc_U0_vconv_xlim_out_out_din),
    .vconv_xlim_out_out_full_n(vconv_xlim_loc_c_full_n),
    .vconv_xlim_out_out_write(Block_proc_U0_vconv_xlim_out_out_write)
);

Loop_HConvH_proc6 Loop_HConvH_proc6_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Loop_HConvH_proc6_U0_ap_start),
    .start_full_n(start_for_Loop_VConvH_proc_U0_full_n),
    .ap_done(Loop_HConvH_proc6_U0_ap_done),
    .ap_continue(Loop_HConvH_proc6_U0_ap_continue),
    .ap_idle(Loop_HConvH_proc6_U0_ap_idle),
    .ap_ready(Loop_HConvH_proc6_U0_ap_ready),
    .start_out(Loop_HConvH_proc6_U0_start_out),
    .start_write(Loop_HConvH_proc6_U0_start_write),
    .height_dout(height_c164_dout),
    .height_empty_n(height_c164_empty_n),
    .height_read(Loop_HConvH_proc6_U0_height_read),
    .width_dout(width_c163_dout),
    .width_empty_n(width_c163_empty_n),
    .width_read(Loop_HConvH_proc6_U0_width_read),
    .src_V_TDATA(src_V_TDATA),
    .src_V_TVALID(src_V_TVALID),
    .src_V_TREADY(Loop_HConvH_proc6_U0_src_V_TREADY),
    .hconv_V_din(Loop_HConvH_proc6_U0_hconv_V_din),
    .hconv_V_full_n(hconv_V_full_n),
    .hconv_V_write(Loop_HConvH_proc6_U0_hconv_V_write)
);

Loop_VConvH_proc Loop_VConvH_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Loop_VConvH_proc_U0_ap_start),
    .ap_done(Loop_VConvH_proc_U0_ap_done),
    .ap_continue(Loop_VConvH_proc_U0_ap_continue),
    .ap_idle(Loop_VConvH_proc_U0_ap_idle),
    .ap_ready(Loop_VConvH_proc_U0_ap_ready),
    .height_dout(height_c166_dout),
    .height_empty_n(height_c166_empty_n),
    .height_read(Loop_VConvH_proc_U0_height_read),
    .vconv_xlim_loc_dout(vconv_xlim_loc_c_dout),
    .vconv_xlim_loc_empty_n(vconv_xlim_loc_c_empty_n),
    .vconv_xlim_loc_read(Loop_VConvH_proc_U0_vconv_xlim_loc_read),
    .hconv_V_dout(hconv_V_dout),
    .hconv_V_empty_n(hconv_V_empty_n),
    .hconv_V_read(Loop_VConvH_proc_U0_hconv_V_read),
    .vconv_V_din(Loop_VConvH_proc_U0_vconv_V_din),
    .vconv_V_full_n(vconv_V_full_n),
    .vconv_V_write(Loop_VConvH_proc_U0_vconv_V_write),
    .height_out_din(Loop_VConvH_proc_U0_height_out_din),
    .height_out_full_n(height_c167_full_n),
    .height_out_write(Loop_VConvH_proc_U0_height_out_write),
    .vconv_xlim_loc_out_din(Loop_VConvH_proc_U0_vconv_xlim_loc_out_din),
    .vconv_xlim_loc_out_full_n(vconv_xlim_loc_c168_full_n),
    .vconv_xlim_loc_out_write(Loop_VConvH_proc_U0_vconv_xlim_loc_out_write)
);

Loop_Border_proc Loop_Border_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Loop_Border_proc_U0_ap_start),
    .ap_done(Loop_Border_proc_U0_ap_done),
    .ap_continue(Loop_Border_proc_U0_ap_continue),
    .ap_idle(Loop_Border_proc_U0_ap_idle),
    .ap_ready(Loop_Border_proc_U0_ap_ready),
    .width_dout(width_c165_dout),
    .width_empty_n(width_c165_empty_n),
    .width_read(Loop_Border_proc_U0_width_read),
    .height_dout(height_c167_dout),
    .height_empty_n(height_c167_empty_n),
    .height_read(Loop_Border_proc_U0_height_read),
    .dst_V_TDATA(Loop_Border_proc_U0_dst_V_TDATA),
    .dst_V_TVALID(Loop_Border_proc_U0_dst_V_TVALID),
    .dst_V_TREADY(dst_V_TREADY),
    .vconv_xlim_loc_dout(vconv_xlim_loc_c168_dout),
    .vconv_xlim_loc_empty_n(vconv_xlim_loc_c168_empty_n),
    .vconv_xlim_loc_read(Loop_Border_proc_U0_vconv_xlim_loc_read),
    .vconv_V_dout(vconv_V_dout),
    .vconv_V_empty_n(vconv_V_empty_n),
    .vconv_V_read(Loop_Border_proc_U0_vconv_V_read)
);

fifo_w32_d2_A width_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(filter11x11_strm_ent_U0_width_out_din),
    .if_full_n(width_c_full_n),
    .if_write(filter11x11_strm_ent_U0_width_out_write),
    .if_dout(width_c_dout),
    .if_empty_n(width_c_empty_n),
    .if_read(Block_proc_U0_width_read)
);

fifo_w32_d2_A width_c163_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(filter11x11_strm_ent_U0_width_out1_din),
    .if_full_n(width_c163_full_n),
    .if_write(filter11x11_strm_ent_U0_width_out1_write),
    .if_dout(width_c163_dout),
    .if_empty_n(width_c163_empty_n),
    .if_read(Loop_HConvH_proc6_U0_width_read)
);

fifo_w32_d2_A height_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(filter11x11_strm_ent_U0_height_out_din),
    .if_full_n(height_c_full_n),
    .if_write(filter11x11_strm_ent_U0_height_out_write),
    .if_dout(height_c_dout),
    .if_empty_n(height_c_empty_n),
    .if_read(Block_proc_U0_height_read)
);

fifo_w32_d2_A height_c164_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(filter11x11_strm_ent_U0_height_out2_din),
    .if_full_n(height_c164_full_n),
    .if_write(filter11x11_strm_ent_U0_height_out2_write),
    .if_dout(height_c164_dout),
    .if_empty_n(height_c164_empty_n),
    .if_read(Loop_HConvH_proc6_U0_height_read)
);

fifo_w32_d3_A width_c165_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_proc_U0_width_out_din),
    .if_full_n(width_c165_full_n),
    .if_write(Block_proc_U0_width_out_write),
    .if_dout(width_c165_dout),
    .if_empty_n(width_c165_empty_n),
    .if_read(Loop_Border_proc_U0_width_read)
);

fifo_w32_d2_A height_c166_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_proc_U0_height_out_din),
    .if_full_n(height_c166_full_n),
    .if_write(Block_proc_U0_height_out_write),
    .if_dout(height_c166_dout),
    .if_empty_n(height_c166_empty_n),
    .if_read(Loop_VConvH_proc_U0_height_read)
);

fifo_w32_d2_A vconv_xlim_loc_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_proc_U0_vconv_xlim_out_out_din),
    .if_full_n(vconv_xlim_loc_c_full_n),
    .if_write(Block_proc_U0_vconv_xlim_out_out_write),
    .if_dout(vconv_xlim_loc_c_dout),
    .if_empty_n(vconv_xlim_loc_c_empty_n),
    .if_read(Loop_VConvH_proc_U0_vconv_xlim_loc_read)
);

fifo_w32_d2_A hconv_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_HConvH_proc6_U0_hconv_V_din),
    .if_full_n(hconv_V_full_n),
    .if_write(Loop_HConvH_proc6_U0_hconv_V_write),
    .if_dout(hconv_V_dout),
    .if_empty_n(hconv_V_empty_n),
    .if_read(Loop_VConvH_proc_U0_hconv_V_read)
);

fifo_w32_d2_A vconv_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_VConvH_proc_U0_vconv_V_din),
    .if_full_n(vconv_V_full_n),
    .if_write(Loop_VConvH_proc_U0_vconv_V_write),
    .if_dout(vconv_V_dout),
    .if_empty_n(vconv_V_empty_n),
    .if_read(Loop_Border_proc_U0_vconv_V_read)
);

fifo_w32_d2_A height_c167_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_VConvH_proc_U0_height_out_din),
    .if_full_n(height_c167_full_n),
    .if_write(Loop_VConvH_proc_U0_height_out_write),
    .if_dout(height_c167_dout),
    .if_empty_n(height_c167_empty_n),
    .if_read(Loop_Border_proc_U0_height_read)
);

fifo_w32_d2_A vconv_xlim_loc_c168_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_VConvH_proc_U0_vconv_xlim_loc_out_din),
    .if_full_n(vconv_xlim_loc_c168_full_n),
    .if_write(Loop_VConvH_proc_U0_vconv_xlim_loc_out_write),
    .if_dout(vconv_xlim_loc_c168_dout),
    .if_empty_n(vconv_xlim_loc_c168_empty_n),
    .if_read(Loop_Border_proc_U0_vconv_xlim_loc_read)
);

start_for_Block_pmb6 start_for_Block_pmb6_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Block_proc_U0_din),
    .if_full_n(start_for_Block_proc_U0_full_n),
    .if_write(filter11x11_strm_ent_U0_start_write),
    .if_dout(start_for_Block_proc_U0_dout),
    .if_empty_n(start_for_Block_proc_U0_empty_n),
    .if_read(Block_proc_U0_ap_ready)
);

start_for_Loop_Boncg start_for_Loop_Boncg_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Loop_Border_proc_U0_din),
    .if_full_n(start_for_Loop_Border_proc_U0_full_n),
    .if_write(Block_proc_U0_start_write),
    .if_dout(start_for_Loop_Border_proc_U0_dout),
    .if_empty_n(start_for_Loop_Border_proc_U0_empty_n),
    .if_read(Loop_Border_proc_U0_ap_ready)
);

start_for_Loop_VCocq start_for_Loop_VCocq_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Loop_VConvH_proc_U0_din),
    .if_full_n(start_for_Loop_VConvH_proc_U0_full_n),
    .if_write(Loop_HConvH_proc6_U0_start_write),
    .if_dout(start_for_Loop_VConvH_proc_U0_dout),
    .if_empty_n(start_for_Loop_VConvH_proc_U0_empty_n),
    .if_read(Loop_VConvH_proc_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_Loop_HConvH_proc6_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_Loop_HConvH_proc6_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_Loop_HConvH_proc6_U0_ap_ready <= ap_sync_Loop_HConvH_proc6_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_filter11x11_strm_ent_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_filter11x11_strm_ent_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_filter11x11_strm_ent_U0_ap_ready <= ap_sync_filter11x11_strm_ent_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == Loop_HConvH_proc6_U0_ap_ready) & (ap_sync_ready == 1'b1))) begin
        Loop_HConvH_proc6_U0_ap_ready_count <= (Loop_HConvH_proc6_U0_ap_ready_count - 2'd1);
    end else if (((1'b1 == Loop_HConvH_proc6_U0_ap_ready) & (ap_sync_ready == 1'b0))) begin
        Loop_HConvH_proc6_U0_ap_ready_count <= (Loop_HConvH_proc6_U0_ap_ready_count + 2'd1);
    end
end

always @ (posedge ap_clk) begin
    if (((ap_sync_ready == 1'b1) & (filter11x11_strm_ent_U0_ap_ready == 1'b0))) begin
        filter11x11_strm_ent_U0_ap_ready_count <= (filter11x11_strm_ent_U0_ap_ready_count - 2'd1);
    end else if (((ap_sync_ready == 1'b0) & (filter11x11_strm_ent_U0_ap_ready == 1'b1))) begin
        filter11x11_strm_ent_U0_ap_ready_count <= (filter11x11_strm_ent_U0_ap_ready_count + 2'd1);
    end
end

assign Block_proc_U0_ap_continue = 1'b1;

assign Block_proc_U0_ap_start = start_for_Block_proc_U0_empty_n;

assign Loop_Border_proc_U0_ap_continue = 1'b1;

assign Loop_Border_proc_U0_ap_start = start_for_Loop_Border_proc_U0_empty_n;

assign Loop_Border_proc_U0_start_full_n = 1'b1;

assign Loop_Border_proc_U0_start_write = 1'b0;

assign Loop_HConvH_proc6_U0_ap_continue = 1'b1;

assign Loop_HConvH_proc6_U0_ap_start = ((ap_sync_reg_Loop_HConvH_proc6_U0_ap_ready ^ 1'b1) & ap_start);

assign Loop_VConvH_proc_U0_ap_continue = 1'b1;

assign Loop_VConvH_proc_U0_ap_start = start_for_Loop_VConvH_proc_U0_empty_n;

assign Loop_VConvH_proc_U0_start_full_n = 1'b1;

assign Loop_VConvH_proc_U0_start_write = 1'b0;

assign ap_done = Loop_Border_proc_U0_ap_done;

assign ap_idle = (filter11x11_strm_ent_U0_ap_idle & Loop_VConvH_proc_U0_ap_idle & Loop_HConvH_proc6_U0_ap_idle & Loop_Border_proc_U0_ap_idle & Block_proc_U0_ap_idle);

assign ap_ready = ap_sync_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_Loop_HConvH_proc6_U0_ap_ready = (ap_sync_reg_Loop_HConvH_proc6_U0_ap_ready | Loop_HConvH_proc6_U0_ap_ready);

assign ap_sync_continue = 1'b1;

assign ap_sync_done = Loop_Border_proc_U0_ap_done;

assign ap_sync_filter11x11_strm_ent_U0_ap_ready = (filter11x11_strm_ent_U0_ap_ready | ap_sync_reg_filter11x11_strm_ent_U0_ap_ready);

assign ap_sync_ready = (ap_sync_filter11x11_strm_ent_U0_ap_ready & ap_sync_Loop_HConvH_proc6_U0_ap_ready);

assign dst_V_TDATA = Loop_Border_proc_U0_dst_V_TDATA;

assign dst_V_TVALID = Loop_Border_proc_U0_dst_V_TVALID;

assign filter11x11_strm_ent_U0_ap_continue = 1'b1;

assign filter11x11_strm_ent_U0_ap_start = ((ap_sync_reg_filter11x11_strm_ent_U0_ap_ready ^ 1'b1) & ap_start);

assign src_V_TREADY = Loop_HConvH_proc6_U0_src_V_TREADY;

assign start_for_Block_proc_U0_din = 1'b1;

assign start_for_Loop_Border_proc_U0_din = 1'b1;

assign start_for_Loop_VConvH_proc_U0_din = 1'b1;

endmodule //filter11x11_strm
